{% set name = "python-chromedriver-binary" %}
{% set version = "121.0.6134.0.0" %}
{% set chromedriver_version = version[:-2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 190d2a78ec9c7e00629480aca022307bd85b5fc1f92f873460358f223c427f05
  - url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/{{ chromedriver_version }}/linux64/chromedriver-linux64.zip  # [linux]
    sha256: 6349f1b53ebc2d4d2d599e7f9f98ad6acfa01cac5daf41fbd47a83902e2cf9ca  # [linux]
  - url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/{{ chromedriver_version }}/mac-x64/chromedriver-mac-x64.zip  # [osx]
    sha256: e3a36e23356874cbae98d67b63887b3afd3256de49ace75d3fe9c17f7ae0ce5e  # [osx]
  - url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/{{ chromedriver_version }}/win32/chromedriver-win32.zip  # [win]
    sha256: 8cb856e08c2cee19d4777d12a2f39c995866b4f1a7b1150adec6a79087181f97  # [win]

build:
  number: 0
  script:
    - chmod +x chromedriver  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  entry_points:
    - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  binary_relocation: false  # [osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - chromedriver_binary
  commands:
    - chromedriver-path
    # TODO: investigate on linux, (at least) libxcb is missing... 
    - $(chromedriver-path)/chromedriver --version  # [osx]

about:
  home: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - igortg
    - williamjamir
    - bollwyvl
